### PR TITLE
chinese translation (track to v0.2.6 sha 77eb56b4)

### PR DESCRIPTION
**Pull request by cehnuil**
Frankly speaking, it`s quite hard to translate this.>.<

### CODE REVIEW

**Comment by TideSofDarK** [comment]
Wow. Are you sure this will work? addon_russian.txt doesnt work at all so i have to override addon_english with russian text

**Comment by cehnuil** [comment]
I don`t quite know. But I have translated [Life In Area](https://github.com/ZLOY5/LiA), it worked at all times.

**Comment by TideSofDarK** [comment]
Even russian in LiA doesnt work so im in doubt

**Comment by cehnuil** [comment]
Em, I mean the Chinese translation worked.>.<

**Comment by TideSofDarK** [comment]
Well if its working now then ok. Because Russian translations didn't work for like a week.

**Comment by cehnuil** [comment]
Luckily, the chinese translation worked.

**Comment by TideSofDarK** [comment]
That's good. Do Chinese people enjoy Petri?

**Pull request merged**
