### PR TITLE
chinese translation (fix and add panorama localization)

### PR DESCRIPTION
**Pull request by cehnuil**
Hi, I`am confused with KVN and Petrosyan.
I have googled and have known that KVN denotes 'Club of the funny and inventive' but what does Petrosyan mean, the boxer or ?

### CODE REVIEW

**Comment by cehnuil** [comment]
Oh, just forgot it.
Will I make the translation of the Game Description?

**Comment by K1llMan** [comment]
Petrosyan is age-related russian humorist. His jokes are unfunny for young people, but he is very famous.

It will be good if you make translation. Perhaps later we will made more tips and other desciptions.

**Comment by cehnuil** [comment]
Gotcha.  :smile:

**Comment by TideSofDarK** [comment]
Thanks. However we are still kinda far away from releasing latest version.

**Pull request merged**
